Refactor template

diff --git a/.github/workflows/template-build-linux-x64.yml b/.github/workflows/template-build-linux-x64.yml
--- a/.github/workflows/template-build-linux-x64.yml
+++ b/.github/workflows/template-build-linux-x64.yml
@@ -6,14 +6,19 @@ on:
         required: true
         type: string
         default: 'refs/heads/main'
-      upload_cloudflare_r2:
+      public_provider:
         required: true
-        type: boolean
-        default: false
+        type: string
+        default: none
+        description: 'none: build only, github: build and publish to github, cloudflare: build and publish to cloudflare'
       new_version:
         required: true
         type: string
         default: ''
+      cloudflare_r2_path:
+        required: false
+        type: string
+        default: '/jan-nightly-build/'
     secrets:
       CLOUDFLARE_R2_BUCKET_NAME:
         required: false
@@ -44,8 +49,8 @@ jobs:
       - name: Install jq
         uses: dcarbone/install-jq-action@v2.0.1
 
-      - name: Update app version base on tag
-        id: version_update
+      - name: Update app version base public_provider
+        if: inputs.public_provider != 'github'
         run: |
           echo "Version: ${{ inputs.new_version }}"
           # Update the version in electron/package.json
@@ -53,19 +58,33 @@ jobs:
           mv /tmp/package.json electron/package.json
           jq --arg version "${{ inputs.new_version }}" '.version = $version' web/package.json > /tmp/package.json
           mv /tmp/package.json web/package.json
-          jq '.build.publish = [{"provider": "s3", "bucket": "${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}", "region": "auto", "endpoint": "https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com", "path": "/jan-nightly-build/", "channel": "latest"}]' electron/package.json > /tmp/package.json
+          jq '.build.publish = [{"provider": "s3", "bucket": "${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}", "region": "auto", "endpoint": "https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com", "path": "${{ inputs.cloudflare_r2_path }}", "channel": "latest"}]' electron/package.json > /tmp/package.json
           mv /tmp/package.json electron/package.json
           cat electron/package.json
 
-      - name: Build and publish app
+      - name: Update app version base on tag
+        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && inputs.public_provider == 'github'
         run: |
-          # check upload_cloudflare_r2 is true or not
-          if [ "${{ inputs.upload_cloudflare_r2 }}" = "true" ]; then
-            echo "upload_cloudflare_r2 is true"
-            make build-and-publish
+          if [[ ! "${VERSION_TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Tag is not valid!"
+            exit 1
+          fi
+          jq --arg version "${VERSION_TAG#v}" '.version = $version' electron/package.json > /tmp/package.json
+          mv /tmp/package.json electron/package.json
+          jq --arg version "${VERSION_TAG#v}" '.version = $version' web/package.json > /tmp/package.json
+          mv /tmp/package.json web/package.json
+        env:
+          VERSION_TAG: ${{ inputs.new_version }}
+
+      - name: Build and publish app to cloudflare r2 or github artifactory
+        if: inputs.public_provider != 'github'
+        run: |
+          # check public_provider is true or not
+          echo "public_provider is ${{ inputs.public_provider }}"
+          if [ "${{ inputs.public_provider }}" == "none" ]; then
+            make build    
           else
-            echo "upload_cloudflare_r2 is false"
-            make build
+            make build-and-publish
           fi
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -73,13 +92,24 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
           AWS_EC2_METADATA_DISABLED: "true"
 
-      - name: Upload Artifact
+      - name: Build and publish app to github
+        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && inputs.public_provider == 'github'
+        run: |
+          make build-and-publish
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          ANALYTICS_ID: ${{ secrets.JAN_APP_POSTHOG_PROJECT_API_KEY }}
+          ANALYTICS_HOST: ${{ secrets.JAN_APP_POSTHOG_URL }}
+
+      - name: Upload Artifact .deb file
+        if: inputs.public_provider != 'github'
         uses: actions/upload-artifact@v2
         with:
           name: jan-linux-amd64-${{ inputs.new_version }}-deb
           path: ./electron/dist/*.deb
 
-      - name: Upload Artifact
+      - name: Upload Artifact .AppImage file
+        if: inputs.public_provider != 'github'
         uses: actions/upload-artifact@v2
         with:
           name: jan-linux-amd64-${{ inputs.new_version }}-AppImage
diff --git a/.github/workflows/template-build-macos.yml b/.github/workflows/template-build-macos.yml
--- a/.github/workflows/template-build-macos.yml
+++ b/.github/workflows/template-build-macos.yml
@@ -6,14 +6,19 @@ on:
         required: true
         type: string
         default: 'refs/heads/main'
-      upload_cloudflare_r2:
+      public_provider:
         required: true
-        type: boolean
-        default: false
+        type: string
+        default: none
+        description: 'none: build only, github: build and publish to github, cloudflare: build and publish to cloudflare'
       new_version:
         required: true
         type: string
         default: ''
+      cloudflare_r2_path:
+        required: false
+        type: string
+        default: '/jan-nightly-build/'
     secrets:
       CLOUDFLARE_R2_BUCKET_NAME:
         required: false
@@ -54,9 +59,8 @@ jobs:
       - name: Install jq
         uses: dcarbone/install-jq-action@v2.0.1
 
-
       - name: Update app version based on latest release tag with build number
-        id: version_update
+        if: inputs.public_provider != 'github'
         run: |
           echo "Version: ${{ inputs.new_version }}"
           # Update the version in electron/package.json
@@ -66,9 +70,23 @@ jobs:
           jq --arg version "${{ inputs.new_version }}" '.version = $version' web/package.json > /tmp/package.json
           mv /tmp/package.json web/package.json
 
-          jq '.build.publish = [{"provider": "s3", "bucket": "${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}", "region": "auto", "endpoint": "https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com", "path": "/jan-nightly-build/", "channel": "latest"}]' electron/package.json > /tmp/package.json
+          jq '.build.publish = [{"provider": "s3", "bucket": "${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}", "region": "auto", "endpoint": "https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com", "path": "${{ inputs.cloudflare_r2_path }}", "channel": "latest"}]' electron/package.json > /tmp/package.json
           mv /tmp/package.json electron/package.json
           cat electron/package.json
+
+      - name: Update app version base on tag
+        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && inputs.public_provider == 'github'
+        run: |
+          if [[ ! "${VERSION_TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "Error: Tag is not valid!"
+              exit 1
+          fi
+          jq --arg version "${VERSION_TAG#v}" '.version = $version' electron/package.json > /tmp/package.json
+          mv /tmp/package.json electron/package.json
+          jq --arg version "${VERSION_TAG#v}" '.version = $version' web/package.json > /tmp/package.json
+          mv /tmp/package.json web/package.json
+        env:
+          VERSION_TAG: ${{ inputs.new_version }}
 
       - name: Get Cer for code signing
         run: base64 -d <<< "$CODE_SIGN_P12_BASE64" > /tmp/codesign.p12
@@ -82,15 +100,15 @@ jobs:
           p12-file-base64: ${{ secrets.CODE_SIGN_P12_BASE64 }}
           p12-password: ${{ secrets.CODE_SIGN_P12_PASSWORD }}
 
-      - name: Build and publish app
+      - name: Build and publish app to cloudflare r2 or github artifactory
+        if: inputs.public_provider != 'github'
         run: |
-          # check upload_cloudflare_r2 is true or not
-          if [ "${{ inputs.upload_cloudflare_r2 }}" = "true" ]; then
-            echo "upload_cloudflare_r2 is true"
-            make build-and-publish
+          # check public_provider is true or not
+          echo "public_provider is ${{ inputs.public_provider }}"
+          if [ "${{ inputs.public_provider }}" == "none" ]; then
+            make build    
           else
-            echo "upload_cloudflare_r2 is false"
-            make build
+            make build-and-publish
           fi
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -106,13 +124,31 @@ jobs:
           AWS_DEFAULT_REGION: auto
           AWS_EC2_METADATA_DISABLED: "true"
 
+      - name: Build and publish app to github
+        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && inputs.public_provider == 'github'
+        run: |
+          make build-and-publish
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          CSC_LINK: "/tmp/codesign.p12"
+          CSC_KEY_PASSWORD: ${{ secrets.CODE_SIGN_P12_PASSWORD }}
+          CSC_IDENTITY_AUTO_DISCOVERY: "true"
+          APPLE_ID: ${{ secrets.APPLE_ID }}
+          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
+          APP_PATH: "."
+          DEVELOPER_ID: ${{ secrets.DEVELOPER_ID }}
+          ANALYTICS_ID: ${{ secrets.JAN_APP_POSTHOG_PROJECT_API_KEY }}
+          ANALYTICS_HOST: ${{ secrets.JAN_APP_POSTHOG_URL }}
+
       - name: Upload Artifact
+        if: inputs.public_provider != 'github'
         uses: actions/upload-artifact@v2
         with:
           name: jan-mac-x64-${{ inputs.new_version }}
           path: ./electron/dist/jan-mac-x64-${{ inputs.new_version }}.dmg
 
       - name: Upload Artifact
+        if: inputs.public_provider != 'github'
         uses: actions/upload-artifact@v2
         with:
           name: jan-mac-arm64-${{ inputs.new_version }}
diff --git a/.github/workflows/template-build-windows-x64.yml b/.github/workflows/template-build-windows-x64.yml
--- a/.github/workflows/template-build-windows-x64.yml
+++ b/.github/workflows/template-build-windows-x64.yml
@@ -6,14 +6,19 @@ on:
         required: true
         type: string
         default: 'refs/heads/main'
-      upload_cloudflare_r2:
+      public_provider:
         required: true
-        type: boolean
-        default: false
+        type: string
+        default: none
+        description: 'none: build only, github: build and publish to github, cloudflare: build and publish to cloudflare'
       new_version:
         required: true
         type: string
         default: ''
+      cloudflare_r2_path:
+        required: false
+        type: string
+        default: '/jan-nightly-build/'
     secrets:
       CLOUDFLARE_R2_BUCKET_NAME:
         required: false
@@ -54,6 +59,7 @@ jobs:
         uses: dcarbone/install-jq-action@v2.0.1
 
       - name: Update app version base on tag
+        if: inputs.public_provider != 'github'
         id: version_update
         shell: bash
         run: |
@@ -65,20 +71,45 @@ jobs:
           jq --arg version "${{ inputs.new_version }}" '.version = $version' web/package.json > /tmp/package.json
           mv /tmp/package.json web/package.json
 
-          jq '.build.publish = [{"provider": "s3", "bucket": "${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}", "region": "auto", "endpoint": "https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com", "path": "/jan-nightly-build/", "channel": "latest"}]' electron/package.json > /tmp/package.json
+          jq '.build.publish = [{"provider": "s3", "bucket": "${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}", "region": "auto", "endpoint": "https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com", "path": "${{ inputs.cloudflare_r2_path }}", "channel": "latest"}]' electron/package.json > /tmp/package.json
           mv /tmp/package.json electron/package.json
 
           jq '.build.win.sign = "./sign.js"' electron/package.json > /tmp/package.json
           mv /tmp/package.json electron/package.json
           cat electron/package.json
 
+      - name: Update app version base on tag
+        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && inputs.public_provider == 'github'
+        shell: bash
+        run: |
+          if [[ ! "${VERSION_TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "Error: Tag is not valid!"
+              exit 1
+          fi
+          jq --arg version "${VERSION_TAG#v}" '.version = $version' electron/package.json > /tmp/package.json
+          mv /tmp/package.json electron/package.json
+          jq --arg version "${VERSION_TAG#v}" '.version = $version' web/package.json > /tmp/package.json
+          mv /tmp/package.json web/package.json
+          jq '.build.win.sign = "./sign.js"' electron/package.json > /tmp/package.json
+          mv /tmp/package.json electron/package.json
+        env:
+          VERSION_TAG: ${{ inputs.new_version }}
+
       - name: Install AzureSignTool
         run: |
           dotnet tool install --global AzureSignTool
 
-      - name: Build app
+      - name: Build and publish app to cloudflare r2 or github artifactory
+        shell: bash
+        if: inputs.public_provider != 'github'
         run: |
-          make build
+          # check public_provider is true or not
+          echo "public_provider is ${{ inputs.public_provider }}"
+          if [ "${{ inputs.public_provider }}" == "none" ]; then
+            make build    
+          else
+            make build-and-publish
+          fi
         env:
           AZURE_KEY_VAULT_URI: ${{ secrets.AZURE_KEY_VAULT_URI }}
           AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
@@ -90,7 +121,22 @@ jobs:
           AWS_DEFAULT_REGION: auto
           AWS_EC2_METADATA_DISABLED: "true"
 
+      - name: Build app and publish app to github
+        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && inputs.public_provider == 'github'
+        run: |
+          make build-and-publish
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          ANALYTICS_ID: ${{ secrets.JAN_APP_POSTHOG_PROJECT_API_KEY }}
+          ANALYTICS_HOST: ${{ secrets.JAN_APP_POSTHOG_URL }}
+          AZURE_KEY_VAULT_URI: ${{ secrets.AZURE_KEY_VAULT_URI }}
+          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
+          AZURE_CERT_NAME: ${{ secrets.AZURE_CERT_NAME }}
+
       - name: Upload Artifact
+        if: inputs.public_provider != 'github'
         uses: actions/upload-artifact@v2
         with:
           name: jan-win-x64-${{ inputs.new_version }}
